<?php
/**
 * LocationsParamBean
 *
 * PHP version 5
 *
 * @category Class
 * @package  \VoloCommerce\Api\v1
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Volo Public APIs
 *
 * Volo Public APIs
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace VoloCommerce\Api\v1\Model;

use \ArrayAccess;

/**
 * LocationsParamBean Class Doc Comment
 *
 * @category    Class
 * @package     \VoloCommerce\Api\v1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LocationsParamBean implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'LocationsParamBean';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'name' => 'string',
        'parent_id' => 'int',
        'pickable' => 'bool',
        'unavailable_for_listing' => 'bool',
        'physical_location' => 'bool',
        'virtual_stock' => 'bool',
        'picking_priority' => 'int',
        'walk_priority' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'name' => null,
        'parent_id' => 'int32',
        'pickable' => null,
        'unavailable_for_listing' => null,
        'physical_location' => null,
        'virtual_stock' => null,
        'picking_priority' => 'int32',
        'walk_priority' => 'int32'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'name',
        'parent_id' => 'parentId',
        'pickable' => 'pickable',
        'unavailable_for_listing' => 'unavailableForListing',
        'physical_location' => 'physicalLocation',
        'virtual_stock' => 'virtualStock',
        'picking_priority' => 'pickingPriority',
        'walk_priority' => 'walkPriority'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'parent_id' => 'setParentId',
        'pickable' => 'setPickable',
        'unavailable_for_listing' => 'setUnavailableForListing',
        'physical_location' => 'setPhysicalLocation',
        'virtual_stock' => 'setVirtualStock',
        'picking_priority' => 'setPickingPriority',
        'walk_priority' => 'setWalkPriority'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'parent_id' => 'getParentId',
        'pickable' => 'getPickable',
        'unavailable_for_listing' => 'getUnavailableForListing',
        'physical_location' => 'getPhysicalLocation',
        'virtual_stock' => 'getVirtualStock',
        'picking_priority' => 'getPickingPriority',
        'walk_priority' => 'getWalkPriority'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['parent_id'] = isset($data['parent_id']) ? $data['parent_id'] : null;
        $this->container['pickable'] = isset($data['pickable']) ? $data['pickable'] : null;
        $this->container['unavailable_for_listing'] = isset($data['unavailable_for_listing']) ? $data['unavailable_for_listing'] : null;
        $this->container['physical_location'] = isset($data['physical_location']) ? $data['physical_location'] : null;
        $this->container['virtual_stock'] = isset($data['virtual_stock']) ? $data['virtual_stock'] : null;
        $this->container['picking_priority'] = isset($data['picking_priority']) ? $data['picking_priority'] : null;
        $this->container['walk_priority'] = isset($data['walk_priority']) ? $data['walk_priority'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        if ($this->container['name'] === null) {
            $invalid_properties[] = "'name' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['name'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets name
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     * @param string $name
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets parent_id
     * @return int
     */
    public function getParentId()
    {
        return $this->container['parent_id'];
    }

    /**
     * Sets parent_id
     * @param int $parent_id
     * @return $this
     */
    public function setParentId($parent_id)
    {
        $this->container['parent_id'] = $parent_id;

        return $this;
    }

    /**
     * Gets pickable
     * @return bool
     */
    public function getPickable()
    {
        return $this->container['pickable'];
    }

    /**
     * Sets pickable
     * @param bool $pickable
     * @return $this
     */
    public function setPickable($pickable)
    {
        $this->container['pickable'] = $pickable;

        return $this;
    }

    /**
     * Gets unavailable_for_listing
     * @return bool
     */
    public function getUnavailableForListing()
    {
        return $this->container['unavailable_for_listing'];
    }

    /**
     * Sets unavailable_for_listing
     * @param bool $unavailable_for_listing
     * @return $this
     */
    public function setUnavailableForListing($unavailable_for_listing)
    {
        $this->container['unavailable_for_listing'] = $unavailable_for_listing;

        return $this;
    }

    /**
     * Gets physical_location
     * @return bool
     */
    public function getPhysicalLocation()
    {
        return $this->container['physical_location'];
    }

    /**
     * Sets physical_location
     * @param bool $physical_location
     * @return $this
     */
    public function setPhysicalLocation($physical_location)
    {
        $this->container['physical_location'] = $physical_location;

        return $this;
    }

    /**
     * Gets virtual_stock
     * @return bool
     */
    public function getVirtualStock()
    {
        return $this->container['virtual_stock'];
    }

    /**
     * Sets virtual_stock
     * @param bool $virtual_stock
     * @return $this
     */
    public function setVirtualStock($virtual_stock)
    {
        $this->container['virtual_stock'] = $virtual_stock;

        return $this;
    }

    /**
     * Gets picking_priority
     * @return int
     */
    public function getPickingPriority()
    {
        return $this->container['picking_priority'];
    }

    /**
     * Sets picking_priority
     * @param int $picking_priority
     * @return $this
     */
    public function setPickingPriority($picking_priority)
    {
        $this->container['picking_priority'] = $picking_priority;

        return $this;
    }

    /**
     * Gets walk_priority
     * @return int
     */
    public function getWalkPriority()
    {
        return $this->container['walk_priority'];
    }

    /**
     * Sets walk_priority
     * @param int $walk_priority
     * @return $this
     */
    public function setWalkPriority($walk_priority)
    {
        $this->container['walk_priority'] = $walk_priority;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\VoloCommerce\Api\v1\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\VoloCommerce\Api\v1\ObjectSerializer::sanitizeForSerialization($this));
    }
}


