<?php
/**
 * UpdateCustomerRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  \VoloCommerce\Api\v1
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Volo Public APIs
 *
 * Volo Public APIs
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace VoloCommerce\Api\v1\Model;

use \ArrayAccess;

/**
 * UpdateCustomerRequest Class Doc Comment
 *
 * @category    Class
 * @package     \VoloCommerce\Api\v1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UpdateCustomerRequest implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'UpdateCustomerRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'int',
        'name' => 'string',
        'company_name' => 'string',
        'accounts_code' => 'string',
        'vat_number' => 'string',
        'company_reg_number' => 'string',
        'address_line1' => 'string',
        'address_line2' => 'string',
        'city' => 'string',
        'county' => 'string',
        'postcode' => 'string',
        'country' => 'string',
        'email_address' => 'string',
        'phone_number' => 'string',
        'phone_number2' => 'string',
        'phone_number3' => 'string',
        'phone_number4' => 'string',
        'mobile_number' => 'string',
        'fax_number' => 'string',
        'province' => 'string',
        'merchant_type' => 'string',
        'price_level' => 'string',
        'has_account' => 'bool',
        'credit_limit' => 'double',
        'available_credit' => 'double'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => 'int32',
        'name' => null,
        'company_name' => null,
        'accounts_code' => null,
        'vat_number' => null,
        'company_reg_number' => null,
        'address_line1' => null,
        'address_line2' => null,
        'city' => null,
        'county' => null,
        'postcode' => null,
        'country' => null,
        'email_address' => null,
        'phone_number' => null,
        'phone_number2' => null,
        'phone_number3' => null,
        'phone_number4' => null,
        'mobile_number' => null,
        'fax_number' => null,
        'province' => null,
        'merchant_type' => null,
        'price_level' => null,
        'has_account' => null,
        'credit_limit' => 'double',
        'available_credit' => 'double'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'company_name' => 'companyName',
        'accounts_code' => 'accountsCode',
        'vat_number' => 'vatNumber',
        'company_reg_number' => 'companyRegNumber',
        'address_line1' => 'addressLine1',
        'address_line2' => 'addressLine2',
        'city' => 'city',
        'county' => 'county',
        'postcode' => 'postcode',
        'country' => 'country',
        'email_address' => 'emailAddress',
        'phone_number' => 'phoneNumber',
        'phone_number2' => 'phoneNumber2',
        'phone_number3' => 'phoneNumber3',
        'phone_number4' => 'phoneNumber4',
        'mobile_number' => 'mobileNumber',
        'fax_number' => 'faxNumber',
        'province' => 'province',
        'merchant_type' => 'merchantType',
        'price_level' => 'priceLevel',
        'has_account' => 'hasAccount',
        'credit_limit' => 'creditLimit',
        'available_credit' => 'availableCredit'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'company_name' => 'setCompanyName',
        'accounts_code' => 'setAccountsCode',
        'vat_number' => 'setVatNumber',
        'company_reg_number' => 'setCompanyRegNumber',
        'address_line1' => 'setAddressLine1',
        'address_line2' => 'setAddressLine2',
        'city' => 'setCity',
        'county' => 'setCounty',
        'postcode' => 'setPostcode',
        'country' => 'setCountry',
        'email_address' => 'setEmailAddress',
        'phone_number' => 'setPhoneNumber',
        'phone_number2' => 'setPhoneNumber2',
        'phone_number3' => 'setPhoneNumber3',
        'phone_number4' => 'setPhoneNumber4',
        'mobile_number' => 'setMobileNumber',
        'fax_number' => 'setFaxNumber',
        'province' => 'setProvince',
        'merchant_type' => 'setMerchantType',
        'price_level' => 'setPriceLevel',
        'has_account' => 'setHasAccount',
        'credit_limit' => 'setCreditLimit',
        'available_credit' => 'setAvailableCredit'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'company_name' => 'getCompanyName',
        'accounts_code' => 'getAccountsCode',
        'vat_number' => 'getVatNumber',
        'company_reg_number' => 'getCompanyRegNumber',
        'address_line1' => 'getAddressLine1',
        'address_line2' => 'getAddressLine2',
        'city' => 'getCity',
        'county' => 'getCounty',
        'postcode' => 'getPostcode',
        'country' => 'getCountry',
        'email_address' => 'getEmailAddress',
        'phone_number' => 'getPhoneNumber',
        'phone_number2' => 'getPhoneNumber2',
        'phone_number3' => 'getPhoneNumber3',
        'phone_number4' => 'getPhoneNumber4',
        'mobile_number' => 'getMobileNumber',
        'fax_number' => 'getFaxNumber',
        'province' => 'getProvince',
        'merchant_type' => 'getMerchantType',
        'price_level' => 'getPriceLevel',
        'has_account' => 'getHasAccount',
        'credit_limit' => 'getCreditLimit',
        'available_credit' => 'getAvailableCredit'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    const MERCHANT_TYPE_RETAIL = 'RETAIL';
    const MERCHANT_TYPE_TRADE = 'TRADE';
    const MERCHANT_TYPE_FITTING = 'FITTING';
    const PRICE_LEVEL_RETAIL = 'RETAIL';
    const PRICE_LEVEL_POS = 'POS';
    const PRICE_LEVEL_TRADE = 'TRADE';
    const PRICE_LEVEL_TRADE_2 = 'TRADE 2';
    const PRICE_LEVEL_WEB_SITE = 'WEB SITE';
    const PRICE_LEVEL_EBAY_BUY_IT_NOW_PRICE = 'EBAY BUY IT NOW PRICE';
    const PRICE_LEVEL_EBAY_INVENTORY_PRICE = 'EBAY INVENTORY PRICE';
    const PRICE_LEVEL_RRP = 'RRP';
    const PRICE_LEVEL_AMAZON_PRICE = 'AMAZON PRICE';
    

    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getMerchantTypeAllowableValues()
    {
        return [
            self::MERCHANT_TYPE_RETAIL,
            self::MERCHANT_TYPE_TRADE,
            self::MERCHANT_TYPE_FITTING,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getPriceLevelAllowableValues()
    {
        return [
            self::PRICE_LEVEL_RETAIL,
            self::PRICE_LEVEL_POS,
            self::PRICE_LEVEL_TRADE,
            self::PRICE_LEVEL_TRADE_2,
            self::PRICE_LEVEL_WEB_SITE,
            self::PRICE_LEVEL_EBAY_BUY_IT_NOW_PRICE,
            self::PRICE_LEVEL_EBAY_INVENTORY_PRICE,
            self::PRICE_LEVEL_RRP,
            self::PRICE_LEVEL_AMAZON_PRICE,
        ];
    }
    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['company_name'] = isset($data['company_name']) ? $data['company_name'] : null;
        $this->container['accounts_code'] = isset($data['accounts_code']) ? $data['accounts_code'] : null;
        $this->container['vat_number'] = isset($data['vat_number']) ? $data['vat_number'] : null;
        $this->container['company_reg_number'] = isset($data['company_reg_number']) ? $data['company_reg_number'] : null;
        $this->container['address_line1'] = isset($data['address_line1']) ? $data['address_line1'] : null;
        $this->container['address_line2'] = isset($data['address_line2']) ? $data['address_line2'] : null;
        $this->container['city'] = isset($data['city']) ? $data['city'] : null;
        $this->container['county'] = isset($data['county']) ? $data['county'] : null;
        $this->container['postcode'] = isset($data['postcode']) ? $data['postcode'] : null;
        $this->container['country'] = isset($data['country']) ? $data['country'] : null;
        $this->container['email_address'] = isset($data['email_address']) ? $data['email_address'] : null;
        $this->container['phone_number'] = isset($data['phone_number']) ? $data['phone_number'] : null;
        $this->container['phone_number2'] = isset($data['phone_number2']) ? $data['phone_number2'] : null;
        $this->container['phone_number3'] = isset($data['phone_number3']) ? $data['phone_number3'] : null;
        $this->container['phone_number4'] = isset($data['phone_number4']) ? $data['phone_number4'] : null;
        $this->container['mobile_number'] = isset($data['mobile_number']) ? $data['mobile_number'] : null;
        $this->container['fax_number'] = isset($data['fax_number']) ? $data['fax_number'] : null;
        $this->container['province'] = isset($data['province']) ? $data['province'] : null;
        $this->container['merchant_type'] = isset($data['merchant_type']) ? $data['merchant_type'] : null;
        $this->container['price_level'] = isset($data['price_level']) ? $data['price_level'] : null;
        $this->container['has_account'] = isset($data['has_account']) ? $data['has_account'] : null;
        $this->container['credit_limit'] = isset($data['credit_limit']) ? $data['credit_limit'] : null;
        $this->container['available_credit'] = isset($data['available_credit']) ? $data['available_credit'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        $allowed_values = $this->getMerchantTypeAllowableValues();
        if (!in_array($this->container['merchant_type'], $allowed_values)) {
            $invalid_properties[] = sprintf(
                "invalid value for 'merchant_type', must be one of '%s'",
                implode("', '", $allowed_values)
            );
        }

        $allowed_values = $this->getPriceLevelAllowableValues();
        if (!in_array($this->container['price_level'], $allowed_values)) {
            $invalid_properties[] = sprintf(
                "invalid value for 'price_level', must be one of '%s'",
                implode("', '", $allowed_values)
            );
        }

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        $allowed_values = $this->getMerchantTypeAllowableValues();
        if (!in_array($this->container['merchant_type'], $allowed_values)) {
            return false;
        }
        $allowed_values = $this->getPriceLevelAllowableValues();
        if (!in_array($this->container['price_level'], $allowed_values)) {
            return false;
        }
        return true;
    }


    /**
     * Gets id
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     * @param int $id
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     * @param string $name
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets company_name
     * @return string
     */
    public function getCompanyName()
    {
        return $this->container['company_name'];
    }

    /**
     * Sets company_name
     * @param string $company_name
     * @return $this
     */
    public function setCompanyName($company_name)
    {
        $this->container['company_name'] = $company_name;

        return $this;
    }

    /**
     * Gets accounts_code
     * @return string
     */
    public function getAccountsCode()
    {
        return $this->container['accounts_code'];
    }

    /**
     * Sets accounts_code
     * @param string $accounts_code
     * @return $this
     */
    public function setAccountsCode($accounts_code)
    {
        $this->container['accounts_code'] = $accounts_code;

        return $this;
    }

    /**
     * Gets vat_number
     * @return string
     */
    public function getVatNumber()
    {
        return $this->container['vat_number'];
    }

    /**
     * Sets vat_number
     * @param string $vat_number
     * @return $this
     */
    public function setVatNumber($vat_number)
    {
        $this->container['vat_number'] = $vat_number;

        return $this;
    }

    /**
     * Gets company_reg_number
     * @return string
     */
    public function getCompanyRegNumber()
    {
        return $this->container['company_reg_number'];
    }

    /**
     * Sets company_reg_number
     * @param string $company_reg_number
     * @return $this
     */
    public function setCompanyRegNumber($company_reg_number)
    {
        $this->container['company_reg_number'] = $company_reg_number;

        return $this;
    }

    /**
     * Gets address_line1
     * @return string
     */
    public function getAddressLine1()
    {
        return $this->container['address_line1'];
    }

    /**
     * Sets address_line1
     * @param string $address_line1
     * @return $this
     */
    public function setAddressLine1($address_line1)
    {
        $this->container['address_line1'] = $address_line1;

        return $this;
    }

    /**
     * Gets address_line2
     * @return string
     */
    public function getAddressLine2()
    {
        return $this->container['address_line2'];
    }

    /**
     * Sets address_line2
     * @param string $address_line2
     * @return $this
     */
    public function setAddressLine2($address_line2)
    {
        $this->container['address_line2'] = $address_line2;

        return $this;
    }

    /**
     * Gets city
     * @return string
     */
    public function getCity()
    {
        return $this->container['city'];
    }

    /**
     * Sets city
     * @param string $city
     * @return $this
     */
    public function setCity($city)
    {
        $this->container['city'] = $city;

        return $this;
    }

    /**
     * Gets county
     * @return string
     */
    public function getCounty()
    {
        return $this->container['county'];
    }

    /**
     * Sets county
     * @param string $county
     * @return $this
     */
    public function setCounty($county)
    {
        $this->container['county'] = $county;

        return $this;
    }

    /**
     * Gets postcode
     * @return string
     */
    public function getPostcode()
    {
        return $this->container['postcode'];
    }

    /**
     * Sets postcode
     * @param string $postcode
     * @return $this
     */
    public function setPostcode($postcode)
    {
        $this->container['postcode'] = $postcode;

        return $this;
    }

    /**
     * Gets country
     * @return string
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     * @param string $country
     * @return $this
     */
    public function setCountry($country)
    {
        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets email_address
     * @return string
     */
    public function getEmailAddress()
    {
        return $this->container['email_address'];
    }

    /**
     * Sets email_address
     * @param string $email_address
     * @return $this
     */
    public function setEmailAddress($email_address)
    {
        $this->container['email_address'] = $email_address;

        return $this;
    }

    /**
     * Gets phone_number
     * @return string
     */
    public function getPhoneNumber()
    {
        return $this->container['phone_number'];
    }

    /**
     * Sets phone_number
     * @param string $phone_number
     * @return $this
     */
    public function setPhoneNumber($phone_number)
    {
        $this->container['phone_number'] = $phone_number;

        return $this;
    }

    /**
     * Gets phone_number2
     * @return string
     */
    public function getPhoneNumber2()
    {
        return $this->container['phone_number2'];
    }

    /**
     * Sets phone_number2
     * @param string $phone_number2
     * @return $this
     */
    public function setPhoneNumber2($phone_number2)
    {
        $this->container['phone_number2'] = $phone_number2;

        return $this;
    }

    /**
     * Gets phone_number3
     * @return string
     */
    public function getPhoneNumber3()
    {
        return $this->container['phone_number3'];
    }

    /**
     * Sets phone_number3
     * @param string $phone_number3
     * @return $this
     */
    public function setPhoneNumber3($phone_number3)
    {
        $this->container['phone_number3'] = $phone_number3;

        return $this;
    }

    /**
     * Gets phone_number4
     * @return string
     */
    public function getPhoneNumber4()
    {
        return $this->container['phone_number4'];
    }

    /**
     * Sets phone_number4
     * @param string $phone_number4
     * @return $this
     */
    public function setPhoneNumber4($phone_number4)
    {
        $this->container['phone_number4'] = $phone_number4;

        return $this;
    }

    /**
     * Gets mobile_number
     * @return string
     */
    public function getMobileNumber()
    {
        return $this->container['mobile_number'];
    }

    /**
     * Sets mobile_number
     * @param string $mobile_number
     * @return $this
     */
    public function setMobileNumber($mobile_number)
    {
        $this->container['mobile_number'] = $mobile_number;

        return $this;
    }

    /**
     * Gets fax_number
     * @return string
     */
    public function getFaxNumber()
    {
        return $this->container['fax_number'];
    }

    /**
     * Sets fax_number
     * @param string $fax_number
     * @return $this
     */
    public function setFaxNumber($fax_number)
    {
        $this->container['fax_number'] = $fax_number;

        return $this;
    }

    /**
     * Gets province
     * @return string
     */
    public function getProvince()
    {
        return $this->container['province'];
    }

    /**
     * Sets province
     * @param string $province
     * @return $this
     */
    public function setProvince($province)
    {
        $this->container['province'] = $province;

        return $this;
    }

    /**
     * Gets merchant_type
     * @return string
     */
    public function getMerchantType()
    {
        return $this->container['merchant_type'];
    }

    /**
     * Sets merchant_type
     * @param string $merchant_type
     * @return $this
     */
    public function setMerchantType($merchant_type)
    {
        $allowed_values = $this->getMerchantTypeAllowableValues();
        if (!is_null($merchant_type) && !in_array($merchant_type, $allowed_values)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'merchant_type', must be one of '%s'",
                    implode("', '", $allowed_values)
                )
            );
        }
        $this->container['merchant_type'] = $merchant_type;

        return $this;
    }

    /**
     * Gets price_level
     * @return string
     */
    public function getPriceLevel()
    {
        return $this->container['price_level'];
    }

    /**
     * Sets price_level
     * @param string $price_level
     * @return $this
     */
    public function setPriceLevel($price_level)
    {
        $allowed_values = $this->getPriceLevelAllowableValues();
        if (!is_null($price_level) && !in_array($price_level, $allowed_values)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'price_level', must be one of '%s'",
                    implode("', '", $allowed_values)
                )
            );
        }
        $this->container['price_level'] = $price_level;

        return $this;
    }

    /**
     * Gets has_account
     * @return bool
     */
    public function getHasAccount()
    {
        return $this->container['has_account'];
    }

    /**
     * Sets has_account
     * @param bool $has_account
     * @return $this
     */
    public function setHasAccount($has_account)
    {
        $this->container['has_account'] = $has_account;

        return $this;
    }

    /**
     * Gets credit_limit
     * @return double
     */
    public function getCreditLimit()
    {
        return $this->container['credit_limit'];
    }

    /**
     * Sets credit_limit
     * @param double $credit_limit
     * @return $this
     */
    public function setCreditLimit($credit_limit)
    {
        $this->container['credit_limit'] = $credit_limit;

        return $this;
    }

    /**
     * Gets available_credit
     * @return double
     */
    public function getAvailableCredit()
    {
        return $this->container['available_credit'];
    }

    /**
     * Sets available_credit
     * @param double $available_credit
     * @return $this
     */
    public function setAvailableCredit($available_credit)
    {
        $this->container['available_credit'] = $available_credit;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\VoloCommerce\Api\v1\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\VoloCommerce\Api\v1\ObjectSerializer::sanitizeForSerialization($this));
    }
}


