<?php
/**
 * CustomImportLayoutTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  \VoloCommerce\Api\v1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Volo Public APIs
 *
 * Volo Public APIs
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace VoloCommerce\Api\v1;

/**
 * CustomImportLayoutTest Class Doc Comment
 *
 * @category    Class */
// * @description CustomImportLayout
/**
 * @package     \VoloCommerce\Api\v1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CustomImportLayoutTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CustomImportLayout"
     */
    public function testCustomImportLayout()
    {
    }

    /**
     * Test attribute "layout_fields"
     */
    public function testPropertyLayoutFields()
    {
    }

    /**
     * Test attribute "seller_central_category"
     */
    public function testPropertySellerCentralCategory()
    {
    }

    /**
     * Test attribute "seller_central_sub_category"
     */
    public function testPropertySellerCentralSubCategory()
    {
    }

    /**
     * Test attribute "layout_name"
     */
    public function testPropertyLayoutName()
    {
    }

    /**
     * Test attribute "flag_for_new_products"
     */
    public function testPropertyFlagForNewProducts()
    {
    }

    /**
     * Test attribute "skip_existing_product"
     */
    public function testPropertySkipExistingProduct()
    {
    }

    /**
     * Test attribute "skip_new_product"
     */
    public function testPropertySkipNewProduct()
    {
    }

    /**
     * Test attribute "key_field"
     */
    public function testPropertyKeyField()
    {
    }
}
