<?php
/**
 * ImportProductsResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  \VoloCommerce\Api\v1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Volo Public APIs
 *
 * Volo Public APIs
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace VoloCommerce\Api\v1;

/**
 * ImportProductsResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description ImportProductsResponse
/**
 * @package     \VoloCommerce\Api\v1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ImportProductsResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ImportProductsResponse"
     */
    public function testImportProductsResponse()
    {
    }

    /**
     * Test attribute "layout_name"
     */
    public function testPropertyLayoutName()
    {
    }

    /**
     * Test attribute "key_field"
     */
    public function testPropertyKeyField()
    {
    }

    /**
     * Test attribute "total_records"
     */
    public function testPropertyTotalRecords()
    {
    }

    /**
     * Test attribute "total_records_inserted"
     */
    public function testPropertyTotalRecordsInserted()
    {
    }

    /**
     * Test attribute "total_records_updated"
     */
    public function testPropertyTotalRecordsUpdated()
    {
    }

    /**
     * Test attribute "total_records_skipped"
     */
    public function testPropertyTotalRecordsSkipped()
    {
    }

    /**
     * Test attribute "error"
     */
    public function testPropertyError()
    {
    }

    /**
     * Test attribute "page_context"
     */
    public function testPropertyPageContext()
    {
    }
}
