<?php
/**
 * ItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  \VoloCommerce\Api\v1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Volo Public APIs
 *
 * Volo Public APIs
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace VoloCommerce\Api\v1;

/**
 * ItemTest Class Doc Comment
 *
 * @category    Class */
// * @description Item
/**
 * @package     \VoloCommerce\Api\v1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Item"
     */
    public function testItem()
    {
    }

    /**
     * Test attribute "order_item_id"
     */
    public function testPropertyOrderItemId()
    {
    }

    /**
     * Test attribute "web_product_id"
     */
    public function testPropertyWebProductId()
    {
    }

    /**
     * Test attribute "stock_number"
     */
    public function testPropertyStockNumber()
    {
    }

    /**
     * Test attribute "item_number"
     */
    public function testPropertyItemNumber()
    {
    }

    /**
     * Test attribute "product_title"
     */
    public function testPropertyProductTitle()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "unit_cost"
     */
    public function testPropertyUnitCost()
    {
    }

    /**
     * Test attribute "tax_rate"
     */
    public function testPropertyTaxRate()
    {
    }

    /**
     * Test attribute "tax_code"
     */
    public function testPropertyTaxCode()
    {
    }

    /**
     * Test attribute "unit_cost_includes_tax"
     */
    public function testPropertyUnitCostIncludesTax()
    {
    }

    /**
     * Test attribute "weight"
     */
    public function testPropertyWeight()
    {
    }

    /**
     * Test attribute "product_folder_name"
     */
    public function testPropertyProductFolderName()
    {
    }

    /**
     * Test attribute "credit_reason"
     */
    public function testPropertyCreditReason()
    {
    }

    /**
     * Test attribute "custom_message1"
     */
    public function testPropertyCustomMessage1()
    {
    }

    /**
     * Test attribute "custom_message2"
     */
    public function testPropertyCustomMessage2()
    {
    }

    /**
     * Test attribute "custom_message3"
     */
    public function testPropertyCustomMessage3()
    {
    }

    /**
     * Test attribute "location_id"
     */
    public function testPropertyLocationId()
    {
    }

    /**
     * Test attribute "supplier_id"
     */
    public function testPropertySupplierId()
    {
    }

    /**
     * Test attribute "kit_type"
     */
    public function testPropertyKitType()
    {
    }

    /**
     * Test attribute "kit_master"
     */
    public function testPropertyKitMaster()
    {
    }

    /**
     * Test attribute "picked"
     */
    public function testPropertyPicked()
    {
    }

    /**
     * Test attribute "unit_item_tax"
     */
    public function testPropertyUnitItemTax()
    {
    }

    /**
     * Test attribute "unit_shipping_tax"
     */
    public function testPropertyUnitShippingTax()
    {
    }

    /**
     * Test attribute "unit_shipping_amount"
     */
    public function testPropertyUnitShippingAmount()
    {
    }

    /**
     * Test attribute "back_order"
     */
    public function testPropertyBackOrder()
    {
    }
}
