<?php
/**
 * OrderBeanTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  \VoloCommerce\Api\v1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Volo Public APIs
 *
 * Volo Public APIs
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace VoloCommerce\Api\v1;

/**
 * OrderBeanTest Class Doc Comment
 *
 * @category    Class */
// * @description OrderBean
/**
 * @package     \VoloCommerce\Api\v1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderBeanTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OrderBean"
     */
    public function testOrderBean()
    {
    }

    /**
     * Test attribute "order_type"
     */
    public function testPropertyOrderType()
    {
    }

    /**
     * Test attribute "order_source"
     */
    public function testPropertyOrderSource()
    {
    }

    /**
     * Test attribute "esp_order_no"
     */
    public function testPropertyEspOrderNo()
    {
    }

    /**
     * Test attribute "invoice_number"
     */
    public function testPropertyInvoiceNumber()
    {
    }

    /**
     * Test attribute "external_reference"
     */
    public function testPropertyExternalReference()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }

    /**
     * Test attribute "customer_company"
     */
    public function testPropertyCustomerCompany()
    {
    }

    /**
     * Test attribute "customer_name"
     */
    public function testPropertyCustomerName()
    {
    }

    /**
     * Test attribute "customer_address1"
     */
    public function testPropertyCustomerAddress1()
    {
    }

    /**
     * Test attribute "customer_address2"
     */
    public function testPropertyCustomerAddress2()
    {
    }

    /**
     * Test attribute "customer_address3"
     */
    public function testPropertyCustomerAddress3()
    {
    }

    /**
     * Test attribute "customer_city"
     */
    public function testPropertyCustomerCity()
    {
    }

    /**
     * Test attribute "customer_county"
     */
    public function testPropertyCustomerCounty()
    {
    }

    /**
     * Test attribute "customer_postcode"
     */
    public function testPropertyCustomerPostcode()
    {
    }

    /**
     * Test attribute "customer_country"
     */
    public function testPropertyCustomerCountry()
    {
    }

    /**
     * Test attribute "customer_email"
     */
    public function testPropertyCustomerEmail()
    {
    }

    /**
     * Test attribute "customer_telephone"
     */
    public function testPropertyCustomerTelephone()
    {
    }

    /**
     * Test attribute "customer_fax"
     */
    public function testPropertyCustomerFax()
    {
    }

    /**
     * Test attribute "customer_reference"
     */
    public function testPropertyCustomerReference()
    {
    }

    /**
     * Test attribute "customer_notes"
     */
    public function testPropertyCustomerNotes()
    {
    }

    /**
     * Test attribute "delivery_company"
     */
    public function testPropertyDeliveryCompany()
    {
    }

    /**
     * Test attribute "delivery_name"
     */
    public function testPropertyDeliveryName()
    {
    }

    /**
     * Test attribute "delivery_address1"
     */
    public function testPropertyDeliveryAddress1()
    {
    }

    /**
     * Test attribute "delivery_address2"
     */
    public function testPropertyDeliveryAddress2()
    {
    }

    /**
     * Test attribute "delivery_address3"
     */
    public function testPropertyDeliveryAddress3()
    {
    }

    /**
     * Test attribute "delivery_city"
     */
    public function testPropertyDeliveryCity()
    {
    }

    /**
     * Test attribute "delivery_county"
     */
    public function testPropertyDeliveryCounty()
    {
    }

    /**
     * Test attribute "delivery_postcode"
     */
    public function testPropertyDeliveryPostcode()
    {
    }

    /**
     * Test attribute "delivery_country"
     */
    public function testPropertyDeliveryCountry()
    {
    }

    /**
     * Test attribute "delivery_telephone"
     */
    public function testPropertyDeliveryTelephone()
    {
    }

    /**
     * Test attribute "shipping_method"
     */
    public function testPropertyShippingMethod()
    {
    }

    /**
     * Test attribute "shipping_cost"
     */
    public function testPropertyShippingCost()
    {
    }

    /**
     * Test attribute "insurance"
     */
    public function testPropertyInsurance()
    {
    }

    /**
     * Test attribute "discount"
     */
    public function testPropertyDiscount()
    {
    }

    /**
     * Test attribute "voucher_code"
     */
    public function testPropertyVoucherCode()
    {
    }

    /**
     * Test attribute "order_total"
     */
    public function testPropertyOrderTotal()
    {
    }

    /**
     * Test attribute "payment_complete"
     */
    public function testPropertyPaymentComplete()
    {
    }

    /**
     * Test attribute "payments"
     */
    public function testPropertyPayments()
    {
    }

    /**
     * Test attribute "currency_code"
     */
    public function testPropertyCurrencyCode()
    {
    }

    /**
     * Test attribute "exchange_rate"
     */
    public function testPropertyExchangeRate()
    {
    }

    /**
     * Test attribute "seller_username"
     */
    public function testPropertySellerUsername()
    {
    }

    /**
     * Test attribute "seller_id"
     */
    public function testPropertySellerId()
    {
    }

    /**
     * Test attribute "courier_profile_name"
     */
    public function testPropertyCourierProfileName()
    {
    }

    /**
     * Test attribute "buyer_id"
     */
    public function testPropertyBuyerId()
    {
    }

    /**
     * Test attribute "order_items"
     */
    public function testPropertyOrderItems()
    {
    }

    /**
     * Test attribute "store_id"
     */
    public function testPropertyStoreId()
    {
    }

    /**
     * Test attribute "ship_to_store"
     */
    public function testPropertyShipToStore()
    {
    }

    /**
     * Test attribute "order_credits"
     */
    public function testPropertyOrderCredits()
    {
    }

    /**
     * Test attribute "order_status"
     */
    public function testPropertyOrderStatus()
    {
    }

    /**
     * Test attribute "flag1"
     */
    public function testPropertyFlag1()
    {
    }

    /**
     * Test attribute "flag2"
     */
    public function testPropertyFlag2()
    {
    }

    /**
     * Test attribute "courier_name"
     */
    public function testPropertyCourierName()
    {
    }

    /**
     * Test attribute "courier_service"
     */
    public function testPropertyCourierService()
    {
    }

    /**
     * Test attribute "courier_service_code"
     */
    public function testPropertyCourierServiceCode()
    {
    }

    /**
     * Test attribute "fulfilment_type"
     */
    public function testPropertyFulfilmentType()
    {
    }

    /**
     * Test attribute "web_order_id"
     */
    public function testPropertyWebOrderId()
    {
    }

    /**
     * Test attribute "shipping_date"
     */
    public function testPropertyShippingDate()
    {
    }

    /**
     * Test attribute "invoice_date"
     */
    public function testPropertyInvoiceDate()
    {
    }

    /**
     * Test attribute "trade_sale"
     */
    public function testPropertyTradeSale()
    {
    }

    /**
     * Test attribute "courier_tracking"
     */
    public function testPropertyCourierTracking()
    {
    }

    /**
     * Test attribute "actual_courier_cost"
     */
    public function testPropertyActualCourierCost()
    {
    }
}
