<?php
/**
 * OrderCreditDTOTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  \VoloCommerce\Api\v1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Volo Public APIs
 *
 * Volo Public APIs
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace VoloCommerce\Api\v1;

/**
 * OrderCreditDTOTest Class Doc Comment
 *
 * @category    Class */
// * @description OrderCreditDTO
/**
 * @package     \VoloCommerce\Api\v1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderCreditDTOTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OrderCreditDTO"
     */
    public function testOrderCreditDTO()
    {
    }

    /**
     * Test attribute "payment_id"
     */
    public function testPropertyPaymentId()
    {
    }

    /**
     * Test attribute "credit_note_number"
     */
    public function testPropertyCreditNoteNumber()
    {
    }

    /**
     * Test attribute "credit_id"
     */
    public function testPropertyCreditId()
    {
    }

    /**
     * Test attribute "credit_amount"
     */
    public function testPropertyCreditAmount()
    {
    }
}
