<?php
/**
 * ProductBeanTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  \VoloCommerce\Api\v1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Volo Public APIs
 *
 * Volo Public APIs
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace VoloCommerce\Api\v1;

/**
 * ProductBeanTest Class Doc Comment
 *
 * @category    Class */
// * @description ProductBean
/**
 * @package     \VoloCommerce\Api\v1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProductBeanTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProductBean"
     */
    public function testProductBean()
    {
    }

    /**
     * Test attribute "stock_number"
     */
    public function testPropertyStockNumber()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "subtitle"
     */
    public function testPropertySubtitle()
    {
    }

    /**
     * Test attribute "listing_title"
     */
    public function testPropertyListingTitle()
    {
    }

    /**
     * Test attribute "stock_level"
     */
    public function testPropertyStockLevel()
    {
    }

    /**
     * Test attribute "tax_code"
     */
    public function testPropertyTaxCode()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "description2"
     */
    public function testPropertyDescription2()
    {
    }

    /**
     * Test attribute "description3"
     */
    public function testPropertyDescription3()
    {
    }

    /**
     * Test attribute "description4"
     */
    public function testPropertyDescription4()
    {
    }

    /**
     * Test attribute "description5"
     */
    public function testPropertyDescription5()
    {
    }

    /**
     * Test attribute "weight"
     */
    public function testPropertyWeight()
    {
    }

    /**
     * Test attribute "width"
     */
    public function testPropertyWidth()
    {
    }

    /**
     * Test attribute "height"
     */
    public function testPropertyHeight()
    {
    }

    /**
     * Test attribute "depth"
     */
    public function testPropertyDepth()
    {
    }

    /**
     * Test attribute "allow_pre_order"
     */
    public function testPropertyAllowPreOrder()
    {
    }

    /**
     * Test attribute "upc"
     */
    public function testPropertyUpc()
    {
    }

    /**
     * Test attribute "publisher"
     */
    public function testPropertyPublisher()
    {
    }

    /**
     * Test attribute "isbn"
     */
    public function testPropertyIsbn()
    {
    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {
    }

    /**
     * Test attribute "supplier"
     */
    public function testPropertySupplier()
    {
    }

    /**
     * Test attribute "cost_price"
     */
    public function testPropertyCostPrice()
    {
    }

    /**
     * Test attribute "default_delivery_location"
     */
    public function testPropertyDefaultDeliveryLocation()
    {
    }

    /**
     * Test attribute "supplier_sku"
     */
    public function testPropertySupplierSku()
    {
    }

    /**
     * Test attribute "rrp2"
     */
    public function testPropertyRrp2()
    {
    }

    /**
     * Test attribute "rrp3"
     */
    public function testPropertyRrp3()
    {
    }

    /**
     * Test attribute "rrp"
     */
    public function testPropertyRrp()
    {
    }
}
