<?php
/**
 * RefundSalesOrderResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  \VoloCommerce\Api\v1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Volo Public APIs
 *
 * Volo Public APIs
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace VoloCommerce\Api\v1;

/**
 * RefundSalesOrderResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description RefundSalesOrderResponse
/**
 * @package     \VoloCommerce\Api\v1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RefundSalesOrderResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "RefundSalesOrderResponse"
     */
    public function testRefundSalesOrderResponse()
    {
    }

    /**
     * Test attribute "esp_order_no"
     */
    public function testPropertyEspOrderNo()
    {
    }

    /**
     * Test attribute "order_cancelled"
     */
    public function testPropertyOrderCancelled()
    {
    }

    /**
     * Test attribute "order_credits"
     */
    public function testPropertyOrderCredits()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "messages"
     */
    public function testPropertyMessages()
    {
    }
}
