<?php
/**
 * UpdateCustomerRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  \VoloCommerce\Api\v1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Volo Public APIs
 *
 * Volo Public APIs
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace VoloCommerce\Api\v1;

/**
 * UpdateCustomerRequestTest Class Doc Comment
 *
 * @category    Class */
// * @description UpdateCustomerRequest
/**
 * @package     \VoloCommerce\Api\v1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UpdateCustomerRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UpdateCustomerRequest"
     */
    public function testUpdateCustomerRequest()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "company_name"
     */
    public function testPropertyCompanyName()
    {
    }

    /**
     * Test attribute "accounts_code"
     */
    public function testPropertyAccountsCode()
    {
    }

    /**
     * Test attribute "vat_number"
     */
    public function testPropertyVatNumber()
    {
    }

    /**
     * Test attribute "company_reg_number"
     */
    public function testPropertyCompanyRegNumber()
    {
    }

    /**
     * Test attribute "address_line1"
     */
    public function testPropertyAddressLine1()
    {
    }

    /**
     * Test attribute "address_line2"
     */
    public function testPropertyAddressLine2()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "county"
     */
    public function testPropertyCounty()
    {
    }

    /**
     * Test attribute "postcode"
     */
    public function testPropertyPostcode()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "email_address"
     */
    public function testPropertyEmailAddress()
    {
    }

    /**
     * Test attribute "phone_number"
     */
    public function testPropertyPhoneNumber()
    {
    }

    /**
     * Test attribute "phone_number2"
     */
    public function testPropertyPhoneNumber2()
    {
    }

    /**
     * Test attribute "phone_number3"
     */
    public function testPropertyPhoneNumber3()
    {
    }

    /**
     * Test attribute "phone_number4"
     */
    public function testPropertyPhoneNumber4()
    {
    }

    /**
     * Test attribute "mobile_number"
     */
    public function testPropertyMobileNumber()
    {
    }

    /**
     * Test attribute "fax_number"
     */
    public function testPropertyFaxNumber()
    {
    }

    /**
     * Test attribute "province"
     */
    public function testPropertyProvince()
    {
    }

    /**
     * Test attribute "merchant_type"
     */
    public function testPropertyMerchantType()
    {
    }

    /**
     * Test attribute "price_level"
     */
    public function testPropertyPriceLevel()
    {
    }

    /**
     * Test attribute "has_account"
     */
    public function testPropertyHasAccount()
    {
    }

    /**
     * Test attribute "credit_limit"
     */
    public function testPropertyCreditLimit()
    {
    }

    /**
     * Test attribute "available_credit"
     */
    public function testPropertyAvailableCredit()
    {
    }
}
