<?php
/**
 * UpdateLocationBeanTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  \VoloCommerce\Api\v1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Volo Public APIs
 *
 * Volo Public APIs
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace VoloCommerce\Api\v1;

/**
 * UpdateLocationBeanTest Class Doc Comment
 *
 * @category    Class */
// * @description UpdateLocationBean
/**
 * @package     \VoloCommerce\Api\v1
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UpdateLocationBeanTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UpdateLocationBean"
     */
    public function testUpdateLocationBean()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "pickable"
     */
    public function testPropertyPickable()
    {
    }

    /**
     * Test attribute "unavailable_for_listing"
     */
    public function testPropertyUnavailableForListing()
    {
    }

    /**
     * Test attribute "physical_location"
     */
    public function testPropertyPhysicalLocation()
    {
    }

    /**
     * Test attribute "virtual_stock"
     */
    public function testPropertyVirtualStock()
    {
    }

    /**
     * Test attribute "picking_priority"
     */
    public function testPropertyPickingPriority()
    {
    }

    /**
     * Test attribute "walk_priority"
     */
    public function testPropertyWalkPriority()
    {
    }
}
