<?php
/**
 * WebhooksApiTest
 * PHP version 5
 *
 * @category Class
 * @package  \VoloCommerce\Api\v1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Volo Public APIs
 *
 * Volo Public APIs
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace VoloCommerce\Api\v1;

use \VoloCommerce\Api\v1\Configuration;
use \VoloCommerce\Api\v1\ApiClient;
use \VoloCommerce\Api\v1\ApiException;
use \VoloCommerce\Api\v1\ObjectSerializer;

/**
 * WebhooksApiTest Class Doc Comment
 *
 * @category Class
 * @package  \VoloCommerce\Api\v1
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class WebhooksApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createHook
     *
     * Returns registed webhook id.
     *
     */
    public function testCreateHook()
    {
    }

    /**
     * Test case for doDelete
     *
     * Delete registered webhook.
     *
     */
    public function testDoDelete()
    {
    }

    /**
     * Test case for getAvailableEvents
     *
     * Returns list of available events.
     *
     */
    public function testGetAvailableEvents()
    {
    }

    /**
     * Test case for getAvailableScope
     *
     * Returns list of available scopes.
     *
     */
    public function testGetAvailableScope()
    {
    }

    /**
     * Test case for getWebHooks
     *
     * Returns registered webhooks.
     *
     */
    public function testGetWebHooks()
    {
    }

    /**
     * Test case for updateWebhooks
     *
     * Update registered webhook.
     *
     */
    public function testUpdateWebhooks()
    {
    }
}
